### PR TITLE
Session 03 HW

### PR DESCRIPTION
**Pull request by robalford**
I put my homework for session 03 in calculator/calculator.py. Instructions for using the calculator are included in the application's home page html and error response messages. No need to review http_server.py here, next time I'll try making a new git branch for my homework and submitting it from there.

### CODE REVIEW

**Comment by codedragon** [comment]
So, you are missing a readme and tests. I know tests may feel like overkill for a small project like this, but you will be very happy later on, if you get in the habit of creating them now. Refactoring is so much easier when you have tests in place. :) Also, the functionality that Cris actually asked for in the assignment does not exist. I cannot use the url to do math. All that being said, the code looks great. Nice small functions, and well written. Think about how you could allow users to do calculations with more than two numbers.

**Comment by codedragon** [comment]
Cris says it is fine not to have the url part working. :)

**Comment by robalford** [comment]
Ok, thanks, I appreciate the feedback. I thought he'd said in class that we
could use an html form to generate the query string if we wanted, so that's
why I went that route. Will heed your advice re tests. I'm coming to accept
the fact that it's always a good idea to write them :)

**Comment by codedragon** [comment]
I'm not sure if he said anything or not, but I talked to him, and it is all
good to use the forms. :)

On Sun, Jan 31, 2016 at 12:30 PM, robalford <notifications@github.com>
wrote:

> Ok, thanks, I appreciate the feedback. I thought he'd said in class that we
> could use an html form to generate the query string if we wanted, so that's
> why I went that route. Will heed your advice re tests. I'm coming to accept
> the fact that it's always a good idea to write them :)
>
> On Sat, Jan 30, 2016 at 6:53 PM, codedragon <notifications@github.com>
> wrote:
>
> > Cris says it is fine not to have the url part working. :)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/UWPCE-PythonCert/training.python_web/pull/124#issuecomment-177365268
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UWPCE-PythonCert/training.python_web/pull/124#issuecomment-177602355>
> .
>



-- 
Maria Mckinley
Software Developer
www.mariakathryn.net
www.linkedin.com/in/mariamckinley


*NOTICE:* Due to Presidential Executive Orders still not rescinded by
President Obama, the National Security Agency may have read this email
without warning, warrant, or notice, and certainly without probable cause.
They may do this without any judicial or legislative oversight. Click here
to learn more about current US laws and your rights
<http://www.aclu.org/national-security/surveillance-privacy>.

**Pull request closed without merging**
